version: '2'
services:
  user_db:
    image: mysql
    ports:
      - "3009:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: apuesta
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: user
      MYSQL_HOST: user_db
  user_ms:
    build: .
    command: bash -c "sleep 40 && rm -f tmp/pids/server.pid && rails db:migrate && exec rails s -p 4001"
    ports:
      - "4001:4001"
    depends_on:
      - user_db
    environment:
      MYSQL_USER: apuesta
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: user
      MYSQL_HOST: user_db
      PORT: 4001
      RAILS_ENV: production
